### ISSUE TITLE
Error when trying to pull a non existing image

### ISSUE THREAD

**Issue by papey** [factorysh/density#39]
Up the service,

`make run`

Use a task file like : 

```
version: '3'
services:
    hello:
        image: "idonotexist:latest"
        command: "touch /test/answer"
        volumes:
            - "./test:/test"
x-batch:
    max_execution_time: 2s
```

After POST, error is returned by docker, then by runner, etc...

After that, service is in an unstable state, retstarting it crash everything when reading bbolt store for the first time.
